### ISSUE TITLE
Change to return just id

### ISSUE THREAD

**Issue by kasbah** [tracespace/whats-that-gerber#1]
In https://github.com/tracespace/pcb-stackup/issues/11 you asked for a suggestion, I would change it to output just the id and then have an object with the mapping to full names. The object could also include a map for output in different locales so: `whatsThatGerber.fullName[locale][layerId]`. Then again I am not sure I would ever make use of the full names at all. Where do you use them?

**Comment by mcous** [comment]
The reason I included an id and a human readable name is for purposes of a drop-down selection. For example, with svgerber, you upload a layer and select the layer type by the human readable name:

``` html
<select class="UploadList--SelectMenu UploadList--text">
  <option value="tcu">top copper</option>
  <option value="tsm">top soldermask</option>
  <option value="tss">top silkscreen</option>
  <option value="tsp">top solderpaste</option>
  <option value="bcu">bottom copper</option>
  <option value="bsm">bottom soldermask</option>
  <option value="bss">bottom silkscreen</option>
  <option value="bsp">bottom solderpaste</option>
  <option value="icu">inner copper</option>
  <option value="out">board outline</option>
  <option value="drw">gerber drawing</option>
  <option value="drl">drill hits</option>
</select>
```

I like the idea of a locale map! Maybe this?

``` js
whatsThatGerber('board-F_Cu.gbr') // returns 'tcu'
whatsThatGerber.name('tcu') // returns 'top copper'
whatsThatGerber.name('tcu', LOCALE) // returns whatever it's supposed to
```
