### ISSUE TITLE
Add a isValidType static method

### ISSUE THREAD

**Issue by mcous** [tracespace/whats-that-gerber#11]
I noticed in tracespace/pcb-stackup#27 that the only current way to check if a type is valid is to check that it's in `whatsThatGerber.getAllTypes()`. It seems to me that it would be really easy to incorporate this functionality into the whats-that-gerber module itself, and I also think it makes sense to do so

**Comment by kasbah** [comment]
Additionally `getAllTypes()` is a bit of a non-function. Why not just `whatsThatGerber.layerTypes`? It could still be useful to have them enumerated in an array if you are building an interface around the layers.

**Comment by mcous** [comment]
`getAllTypes` is a function because it allows us to easily change the internal representation of the layers without affecting the public API. Exposing a bare array also runs the risk of functionality getting messed up by a poorly written client that edits the array in place (the function returns a new array every time, erasing this risk).

See [some similar methods in the Node crypto library](https://nodejs.org/dist/latest-v6.x/docs/api/crypto.html#crypto_crypto_getciphers)
