### ISSUE TITLE
Extension regexs need end anchor

### ISSUE THREAD

**Issue by mcous** [tracespace/whats-that-gerber#17]
Without the end anchor (e.g. `/.cmp$/`) we can get incorrect matches if the filename happens to have `.${some_matching_extension}` internally. For example, this will match as "top copper":

`foobar.CMPcbDoc.GBS`

Even though it ends in `.GBS`, whats-that-gerber sees the internal `.CMP` and spits out the wrong result.

**Comment by kasbah** [comment]
This was fixed with #17
