### ISSUE TITLE
Match .brd as outline ?

### ISSUE THREAD

**Issue by kasbah** [tracespace/whats-that-gerber#22]
Of course it's also Eagle and other tools board layout file but it's listed [here](http://www.cad2cam.com/list/) as "Mentor Board Outline (Boardstation)" and was mentioned as the default extension for the outline in https://github.com/tracespace/pcb-stackup/issues/48.

**Comment by mcous** [comment]
Unless we see more outlines with `.brd` come in (or get a full set of Boardstation gerbers to compare against) I'm going to say this would be too confusing. Will re-open if that changes
