### ISSUE TITLE
Altium internal planes

### ISSUE THREAD

**Issue by ju5t** [tracespace/whats-that-gerber#23]
According to the [Altium documentation](https://www.altium.com/documentation/18.0/display/ADES/WorkspaceManager_Dlg-GerberSetup_Form((Gerber+Setup))_AD) internal planes can have an extension of GP[0-9]. I would personally match them in the `icu` layer and change the regex of `(g)` to `(gp?)`. What do you think?

Code ref: [index.js#L80](https://github.com/tracespace/whats-that-gerber/blob/master/index.js#L80)

**Comment by kasbah** [comment]
Makes sense but you should probably open this issue on https://github.com/tracespace/tracespace as this package has been integrated into a monorepo there.
